version: 2

models:
  - name: jeff_de_bruges_stg
    description: Web scraping results (Jeff de Bruges website)
    columns:
      - name: product_name
        description: Primary key
        tests:
          - unique
          - not_null
      - name: image_url
        description: url link of the product image on the website
      - name: product_url
        description: url link of the product page
      - name: product_price
        description: price of the product, in euros
      - name: product_weight_g
        description: weight (in grams) of the product

  - name: maison_du_chocolat_stg
    description: Web scraping results (Maison du chocolat website)
    columns:
      - name: product_name
        description: Primary key
        tests:
          - unique
          - not_null
      - name: image_url
        description: url link of the product image on the website
      - name: product_url
        description: url link of the product page
      - name: product_price
        description: price of the product, in euros
      - name: product_weight_g
        description: weight (in grams) of the product

  - name: alain_ducasse_stg
    description: Web scraping results (Alain Ducasse website)
    columns:
      - name: product_name
        description: Primary key
        tests:
          - unique
          - not_null
      - name: image_url
        description: url link of the product image on the website
      - name: product_url
        description: url link of the product page
      - name: product_price
        description: price of the product, in euros
      - name: product_weight_g
        description: weight (in grams) of the product

  - name: lindt_stg
    description: Web scraping results (Lindt website)
    columns:
      - name: product_name
        description: Primary key
        tests:
          - unique
          - not_null
      - name: image_url
        description: url link of the product image on the website
      - name: product_url
        description: url link of the product page
      - name: product_price
        description: price of the product, in euros
      - name: product_weight
        description: weight (in grams) of the product